uint64 timestamp                # time since system start (microseconds)
float32 wind_speed_from_hor_sensor
float32 wind_angle_from_hor_sensor

float32 wind_speed_from_ver_sensor
float32 wind_angle_from_ver_sensor

float32[3] attitude

float32[3] ground_speed

float64 lat			# Latitude, (degrees)
float64 lon			# Longitude, (degrees)
float32 alt

float32[3] wind_speed_calculated

float32 wind_speed_hor_calculated
float32 wind_angle_hor_calculated
